### ISSUE TITLE
Loading the questionnaire seems to fail pretty reliably

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/Bug-Reports-and-Requests#37]
**Bug Report**
The loading of the questionnaire into the current hutch python session failed

**Expected Behavior**
It should work

**Steps To Reproduce**
loading xcs3 or xpp3

**Your Environment**
working as hutchopr.

**Comment by klauer** [comment]
Any messages on failure that could help in debugging this?

**Comment by ZLLentz** [comment]
Hi Silke, is this just an error message that pops up? Or is there a specific experiment that you know should have loaded a motor but did not? We're having trouble locating run 18 questionnaires where the CDS tab has been filled out.

**Comment by klauer** [comment]
The only even partially filled out experiment I had found was `xcsx41018`, which does _rightfully_ show error messages while loading. Those messages are terse/confusing and need reworking, which I'll make an attempt at.

Given that the issue is a couple months old without enough detail to be actionable, I'm going to close this for now. If you have further context to add, please re-open or create a new issue with details.

**Comment by silkenelson** [comment]
I have decided to close this and open a few more targeted requests.
